"""Spatial RNA velocity analysis helpers.

This module keeps the ScrnaClaw `spatial-velocity` skill aligned with the
newer method-aware template used by other spatial skills:

- shared preprocessing controls are explicit and part of the result contract
- each method returns the same summary / table export payloads
- scVelo and VELOVI method-specific core parameters are exposed separately
"""

from __future__ import annotations

import logging

import numpy as np
import pandas as pd

from .dependency_manager import require

logger = logging.getLogger(__name__)

SCVELO_METHODS = ("stochastic", "deterministic", "dynamical")
SUPPORTED_METHODS = SCVELO_METHODS + ("velovi",)

COMMON_PREPROCESS_DEFAULTS = {
    "velocity_min_shared_counts": 30,
    "velocity_n_top_genes": 2000,
    "velocity_n_pcs": 30,
    "velocity_n_neighbors": 30,
    "velocity_use_highly_variable": True,
}

COMMON_GRAPH_DEFAULTS = {
    "velocity_graph_n_neighbors": None,
    "velocity_graph_sqrt_transform": None,
    "velocity_graph_approx": None,
}

SCVELO_CORE_DEFAULTS = {
    "velocity_fit_offset": False,
    "velocity_fit_offset2": False,
    "velocity_min_r2": 0.01,
    "velocity_min_likelihood": 0.001,
}

DYNAMICAL_DEFAULTS = {
    "dynamical_n_top_genes": None,
    "dynamical_max_iter": 10,
    "dynamical_fit_time": True,
    "dynamical_fit_scaling": True,
    "dynamical_fit_steady_states": True,
    "dynamical_n_jobs": None,
}

VELOVI_DEFAULTS = {
    "velovi_n_hidden": 256,
    "velovi_n_latent": 10,
    "velovi_n_layers": 1,
    "velovi_dropout_rate": 0.1,
    "velovi_max_epochs": 500,
    "velovi_lr": 0.01,
    "velovi_weight_decay": 0.01,
    "velovi_batch_size": 256,
    "velovi_n_samples": 25,
    "velovi_early_stopping": True,
}

METHOD_PARAM_DEFAULTS = {
    "stochastic": {
        **COMMON_PREPROCESS_DEFAULTS,
        **COMMON_GRAPH_DEFAULTS,
        **SCVELO_CORE_DEFAULTS,
    },
    "deterministic": {
        **COMMON_PREPROCESS_DEFAULTS,
        **COMMON_GRAPH_DEFAULTS,
        **SCVELO_CORE_DEFAULTS,
    },
    "dynamical": {
        **COMMON_PREPROCESS_DEFAULTS,
        **COMMON_GRAPH_DEFAULTS,
        **SCVELO_CORE_DEFAULTS,
        **DYNAMICAL_DEFAULTS,
    },
    "velovi": {
        **COMMON_PREPROCESS_DEFAULTS,
        **COMMON_GRAPH_DEFAULTS,
        **VELOVI_DEFAULTS,
    },
}


def validate_velocity_layers(adata) -> None:
    """Raise if the input lacks the required velocity count layers."""
    missing = [key for key in ("spliced", "unspliced") if key not in adata.layers]
    if missing:
        raise ValueError(
            f"Required layers missing: {missing}.\n\n"
            "RNA velocity requires `adata.layers['spliced']` and "
            "`adata.layers['unspliced']`.\n"
            "These are usually generated by velocyto or STARsolo."
        )


def add_demo_velocity_layers(adata) -> None:
    """Attach synthetic spliced / unspliced layers for demo runs only."""
    from scipy import sparse

    x = adata.X
    if sparse.issparse(x):
        x = x.toarray()
    x = np.asarray(x, dtype=np.float32).clip(0)

    rng = np.random.default_rng(42)
    frac = rng.uniform(0.65, 0.85, size=x.shape)
    spliced = (x * frac).astype(np.float32)
    unspliced = (x * (1.0 - frac) + rng.exponential(0.05, size=x.shape)).astype(np.float32)

    adata.layers["spliced"] = spliced
    adata.layers["unspliced"] = unspliced
    logger.info("Added synthetic spliced/unspliced layers for demo use only.")


def _to_numpy(values) -> np.ndarray:
    """Convert pandas / sparse / torch-like containers to a NumPy array."""
    if hasattr(values, "toarray"):
        values = values.toarray()
    elif hasattr(values, "values"):
        values = values.values
    return np.asarray(values)


def _coerce_positive_int(value: int | None, *, minimum: int = 1) -> int | None:
    if value is None:
        return None
    return max(minimum, int(value))


def preprocess_for_velocity(
    adata,
    *,
    min_shared_counts: int = COMMON_PREPROCESS_DEFAULTS["velocity_min_shared_counts"],
    n_top_genes: int = COMMON_PREPROCESS_DEFAULTS["velocity_n_top_genes"],
    n_pcs: int = COMMON_PREPROCESS_DEFAULTS["velocity_n_pcs"],
    n_neighbors: int = COMMON_PREPROCESS_DEFAULTS["velocity_n_neighbors"],
    use_highly_variable: bool = COMMON_PREPROCESS_DEFAULTS["velocity_use_highly_variable"],
) -> dict:
    """Prepare moments and neighbor graph for velocity inference."""
    import scanpy as sc

    scv = require("scvelo", feature="RNA velocity")

    if adata.n_obs < 3 or adata.n_vars < 2:
        raise ValueError("RNA velocity requires at least 3 cells and 2 genes.")

    eff_min_shared_counts = max(0, int(min_shared_counts))
    eff_n_top_genes = max(1, min(int(n_top_genes), adata.n_vars))
    eff_n_pcs = max(2, min(int(n_pcs), adata.n_obs - 1, adata.n_vars - 1))
    eff_n_neighbors = max(2, min(int(n_neighbors), adata.n_obs - 1))

    logger.info(
        "Velocity preprocessing: min_shared_counts=%s, n_top_genes=%s, n_pcs=%s, "
        "n_neighbors=%s, use_highly_variable=%s",
        eff_min_shared_counts,
        eff_n_top_genes,
        eff_n_pcs,
        eff_n_neighbors,
        use_highly_variable,
    )

    scv.pp.filter_and_normalize(adata, min_shared_counts=eff_min_shared_counts)
    sc.pp.log1p(adata)

    if use_highly_variable:
        try:
            sc.pp.highly_variable_genes(adata, n_top_genes=eff_n_top_genes, flavor="seurat")
        except TypeError:
            sc.pp.highly_variable_genes(adata, n_top_genes=eff_n_top_genes)
        except Exception as exc:
            logger.warning("Could not compute highly_variable genes: %s", exc)

    pca_kwargs = {"n_comps": eff_n_pcs}
    if "highly_variable" in adata.var.columns:
        pca_kwargs["use_highly_variable"] = bool(use_highly_variable)
    sc.pp.pca(adata, **pca_kwargs)
    sc.pp.neighbors(adata, n_neighbors=eff_n_neighbors, n_pcs=eff_n_pcs)
    scv.pp.moments(
        adata,
        n_pcs=eff_n_pcs,
        n_neighbors=eff_n_neighbors,
        use_highly_variable=bool(use_highly_variable),
    )

    return {
        "min_shared_counts": eff_min_shared_counts,
        "n_top_genes": eff_n_top_genes,
        "n_pcs": eff_n_pcs,
        "n_neighbors": eff_n_neighbors,
        "use_highly_variable": bool(use_highly_variable),
    }


def _compute_speed(adata) -> pd.Series:
    """Compute per-cell velocity speed and persist it in `adata.obs`."""
    if "velocity_length" in adata.obs.columns:
        speed = pd.to_numeric(adata.obs["velocity_length"], errors="coerce")
        adata.obs["velocity_speed"] = speed.to_numpy()
        return speed

    if "velocity" not in adata.layers:
        return pd.Series(dtype=float)

    velocity = _to_numpy(adata.layers["velocity"]).astype(np.float64, copy=False)
    values = np.sqrt((velocity ** 2).sum(axis=1))
    adata.obs["velocity_speed"] = values
    return pd.Series(values, index=adata.obs_names)


def _count_positive_obs(adata, key: str) -> int | None:
    if key not in adata.obs.columns:
        return None
    values = pd.to_numeric(adata.obs[key], errors="coerce").fillna(0.0).to_numpy()
    return int(np.sum(values > 0))


def _build_cell_df(adata, *, cluster_key: str) -> pd.DataFrame:
    columns: list[str] = []
    if cluster_key in adata.obs.columns:
        columns.append(cluster_key)
    for key in (
        "velocity_speed",
        "velocity_length",
        "velocity_confidence",
        "velocity_confidence_transition",
        "velocity_pseudotime",
        "latent_time",
        "root_cells",
        "end_points",
        "velocity_self_transition",
    ):
        if key in adata.obs.columns and key not in columns:
            columns.append(key)
    if not columns:
        cell_df = pd.DataFrame(index=adata.obs_names)
    else:
        cell_df = adata.obs[columns].copy()
    cell_df.index.name = "cell_id"
    return cell_df


def _build_gene_df(adata) -> pd.DataFrame:
    columns = [
        key
        for key in (
            "velocity_genes",
            "velocity_gamma",
            "velocity_qreg_ratio",
            "velocity_r2",
            "fit_likelihood",
            "fit_alpha",
            "fit_beta",
            "fit_gamma",
            "fit_t_",
            "fit_scaling",
        )
        if key in adata.var.columns
    ]
    if not columns:
        gene_df = pd.DataFrame(index=adata.var_names)
    else:
        gene_df = adata.var[columns].copy()

    sort_by = next((key for key in ("fit_likelihood", "velocity_r2", "velocity_qreg_ratio") if key in gene_df.columns), None)
    if sort_by:
        gene_df = gene_df.sort_values(by=sort_by, ascending=False, na_position="last")
    gene_df.index.name = "gene"
    return gene_df


def _count_velocity_genes(adata, gene_df: pd.DataFrame) -> int | None:
    if "velocity_genes" in adata.var.columns:
        return int(np.sum(adata.var["velocity_genes"].astype(bool)))
    for key in ("fit_likelihood", "velocity_r2", "velocity_gamma", "velocity_qreg_ratio"):
        if key in gene_df.columns:
            return int(pd.to_numeric(gene_df[key], errors="coerce").notna().sum())
    return None


def _finalize_summary(
    adata,
    *,
    method: str,
    engine: str,
    cluster_key: str,
    warnings_list: list[str],
    preprocess_params: dict,
    graph_params: dict,
    model_params: dict,
) -> dict:
    speed = _compute_speed(adata)
    cell_df = _build_cell_df(adata, cluster_key=cluster_key)
    gene_df = _build_gene_df(adata)

    summary = {
        "method": method,
        "engine": engine,
        "cluster_key": cluster_key,
        "n_velocity_genes": _count_velocity_genes(adata, gene_df),
        "mean_speed": float(speed.mean()) if not speed.empty else 0.0,
        "median_speed": float(speed.median()) if not speed.empty else 0.0,
        "mean_confidence": None,
        "n_root_cells": _count_positive_obs(adata, "root_cells"),
        "n_end_points": _count_positive_obs(adata, "end_points"),
        "has_velocity_pseudotime": "velocity_pseudotime" in adata.obs.columns,
        "has_latent_time": "latent_time" in adata.obs.columns,
        "preprocess_params": preprocess_params,
        "graph_params": graph_params,
        "model_params": model_params,
        "warnings": warnings_list,
        "cell_df": cell_df,
        "gene_df": gene_df,
    }

    if "velocity_confidence" in adata.obs.columns:
        confidence = pd.to_numeric(adata.obs["velocity_confidence"], errors="coerce").dropna()
        if not confidence.empty:
            summary["mean_confidence"] = float(confidence.mean())

    return summary


def run_scvelo(
    adata,
    *,
    mode: str = "stochastic",
    cluster_key: str = "leiden",
    velocity_min_shared_counts: int = COMMON_PREPROCESS_DEFAULTS["velocity_min_shared_counts"],
    velocity_n_top_genes: int = COMMON_PREPROCESS_DEFAULTS["velocity_n_top_genes"],
    velocity_n_pcs: int = COMMON_PREPROCESS_DEFAULTS["velocity_n_pcs"],
    velocity_n_neighbors: int = COMMON_PREPROCESS_DEFAULTS["velocity_n_neighbors"],
    velocity_use_highly_variable: bool = COMMON_PREPROCESS_DEFAULTS["velocity_use_highly_variable"],
    velocity_fit_offset: bool = SCVELO_CORE_DEFAULTS["velocity_fit_offset"],
    velocity_fit_offset2: bool = SCVELO_CORE_DEFAULTS["velocity_fit_offset2"],
    velocity_min_r2: float = SCVELO_CORE_DEFAULTS["velocity_min_r2"],
    velocity_min_likelihood: float = SCVELO_CORE_DEFAULTS["velocity_min_likelihood"],
    velocity_graph_n_neighbors: int | None = COMMON_GRAPH_DEFAULTS["velocity_graph_n_neighbors"],
    velocity_graph_sqrt_transform: bool | None = COMMON_GRAPH_DEFAULTS["velocity_graph_sqrt_transform"],
    velocity_graph_approx: bool | None = COMMON_GRAPH_DEFAULTS["velocity_graph_approx"],
    dynamical_n_top_genes: int | None = DYNAMICAL_DEFAULTS["dynamical_n_top_genes"],
    dynamical_max_iter: int = DYNAMICAL_DEFAULTS["dynamical_max_iter"],
    dynamical_fit_time: bool = DYNAMICAL_DEFAULTS["dynamical_fit_time"],
    dynamical_fit_scaling: bool = DYNAMICAL_DEFAULTS["dynamical_fit_scaling"],
    dynamical_fit_steady_states: bool = DYNAMICAL_DEFAULTS["dynamical_fit_steady_states"],
    dynamical_n_jobs: int | None = DYNAMICAL_DEFAULTS["dynamical_n_jobs"],
) -> dict:
    """Run the scVelo backend and return a standardized summary."""
    scv = require("scvelo", feature="RNA velocity")

    warnings_list: list[str] = []
    preprocess_params = preprocess_for_velocity(
        adata,
        min_shared_counts=velocity_min_shared_counts,
        n_top_genes=velocity_n_top_genes,
        n_pcs=velocity_n_pcs,
        n_neighbors=velocity_n_neighbors,
        use_highly_variable=velocity_use_highly_variable,
    )

    if mode == "dynamical":
        recover_kwargs = {
            "var_names": "velocity_genes",
            "max_iter": max(1, int(dynamical_max_iter)),
            "fit_time": bool(dynamical_fit_time),
            "fit_scaling": bool(dynamical_fit_scaling),
            "fit_steady_states": bool(dynamical_fit_steady_states),
            "show_progress_bar": False,
        }
        if dynamical_n_top_genes is not None:
            recover_kwargs["n_top_genes"] = max(1, int(dynamical_n_top_genes))
        if dynamical_n_jobs is not None:
            recover_kwargs["n_jobs"] = max(1, int(dynamical_n_jobs))

        logger.info("Running scVelo recover_dynamics with %s", recover_kwargs)
        scv.tl.recover_dynamics(adata, **recover_kwargs)

    velocity_kwargs = {
        "mode": mode,
        "fit_offset": bool(velocity_fit_offset),
        "fit_offset2": bool(velocity_fit_offset2),
        "min_r2": float(velocity_min_r2),
        "min_likelihood": float(velocity_min_likelihood),
        "use_highly_variable": bool(velocity_use_highly_variable),
    }
    logger.info("Running scVelo velocity with %s", velocity_kwargs)
    scv.tl.velocity(adata, **velocity_kwargs)

    graph_kwargs = {"vkey": "velocity", "show_progress_bar": False}
    if velocity_graph_n_neighbors is not None:
        graph_kwargs["n_neighbors"] = max(1, int(velocity_graph_n_neighbors))
    if velocity_graph_sqrt_transform is not None:
        graph_kwargs["sqrt_transform"] = bool(velocity_graph_sqrt_transform)
    if velocity_graph_approx is not None:
        graph_kwargs["approx"] = bool(velocity_graph_approx)
    if dynamical_n_jobs is not None:
        graph_kwargs["n_jobs"] = max(1, int(dynamical_n_jobs))

    logger.info("Running scVelo velocity_graph with %s", graph_kwargs)
    scv.tl.velocity_graph(adata, **graph_kwargs)

    try:
        scv.tl.velocity_confidence(adata, vkey="velocity")
    except Exception as exc:
        msg = f"velocity_confidence failed: {exc}"
        logger.warning(msg)
        warnings_list.append(msg)

    try:
        scv.tl.velocity_pseudotime(adata, vkey="velocity")
    except Exception as exc:
        msg = f"velocity_pseudotime failed: {exc}"
        logger.warning(msg)
        warnings_list.append(msg)

    if mode == "dynamical":
        try:
            scv.tl.latent_time(adata, vkey="velocity")
        except Exception as exc:
            msg = f"latent_time failed: {exc}"
            logger.warning(msg)
            warnings_list.append(msg)

    graph_params = {
        "n_neighbors": _coerce_positive_int(velocity_graph_n_neighbors),
        "sqrt_transform": velocity_graph_sqrt_transform,
        "approx": velocity_graph_approx,
    }
    model_params = {
        "fit_offset": bool(velocity_fit_offset),
        "fit_offset2": bool(velocity_fit_offset2),
        "min_r2": float(velocity_min_r2),
        "min_likelihood": float(velocity_min_likelihood),
        "use_highly_variable": bool(velocity_use_highly_variable),
    }
    if mode == "dynamical":
        model_params.update(
            {
                "dynamical_n_top_genes": _coerce_positive_int(dynamical_n_top_genes),
                "dynamical_max_iter": max(1, int(dynamical_max_iter)),
                "dynamical_fit_time": bool(dynamical_fit_time),
                "dynamical_fit_scaling": bool(dynamical_fit_scaling),
                "dynamical_fit_steady_states": bool(dynamical_fit_steady_states),
                "dynamical_n_jobs": _coerce_positive_int(dynamical_n_jobs),
            }
        )

    return _finalize_summary(
        adata,
        method=mode,
        engine="scvelo",
        cluster_key=cluster_key,
        warnings_list=warnings_list,
        preprocess_params=preprocess_params,
        graph_params=graph_params,
        model_params=model_params,
    )


def run_velovi(
    adata,
    *,
    cluster_key: str = "leiden",
    velocity_min_shared_counts: int = COMMON_PREPROCESS_DEFAULTS["velocity_min_shared_counts"],
    velocity_n_top_genes: int = COMMON_PREPROCESS_DEFAULTS["velocity_n_top_genes"],
    velocity_n_pcs: int = COMMON_PREPROCESS_DEFAULTS["velocity_n_pcs"],
    velocity_n_neighbors: int = COMMON_PREPROCESS_DEFAULTS["velocity_n_neighbors"],
    velocity_use_highly_variable: bool = COMMON_PREPROCESS_DEFAULTS["velocity_use_highly_variable"],
    velocity_graph_n_neighbors: int | None = COMMON_GRAPH_DEFAULTS["velocity_graph_n_neighbors"],
    velocity_graph_sqrt_transform: bool | None = COMMON_GRAPH_DEFAULTS["velocity_graph_sqrt_transform"],
    velocity_graph_approx: bool | None = COMMON_GRAPH_DEFAULTS["velocity_graph_approx"],
    velovi_n_hidden: int = VELOVI_DEFAULTS["velovi_n_hidden"],
    velovi_n_latent: int = VELOVI_DEFAULTS["velovi_n_latent"],
    velovi_n_layers: int = VELOVI_DEFAULTS["velovi_n_layers"],
    velovi_dropout_rate: float = VELOVI_DEFAULTS["velovi_dropout_rate"],
    velovi_max_epochs: int = VELOVI_DEFAULTS["velovi_max_epochs"],
    velovi_lr: float = VELOVI_DEFAULTS["velovi_lr"],
    velovi_weight_decay: float = VELOVI_DEFAULTS["velovi_weight_decay"],
    velovi_batch_size: int = VELOVI_DEFAULTS["velovi_batch_size"],
    velovi_n_samples: int = VELOVI_DEFAULTS["velovi_n_samples"],
    velovi_early_stopping: bool = VELOVI_DEFAULTS["velovi_early_stopping"],
) -> dict:
    """Run the VELOVI backend and return a standardized summary."""
    require("scvelo", feature="VELOVI preprocessing")
    require("scvi-tools", feature="VELOVI")

    import scvelo as scv
    import torch
    from scvi.external import VELOVI

    warnings_list: list[str] = []
    preprocess_params = preprocess_for_velocity(
        adata,
        min_shared_counts=velocity_min_shared_counts,
        n_top_genes=velocity_n_top_genes,
        n_pcs=velocity_n_pcs,
        n_neighbors=velocity_n_neighbors,
        use_highly_variable=velocity_use_highly_variable,
    )

    try:
        from velovi import preprocess_data as velovi_preprocess_data
    except ImportError:
        velovi_preprocess_data = None

    if velovi_preprocess_data is None:
        msg = "velovi.preprocess_data is unavailable; continuing without VELOVI priors."
        logger.warning(msg)
        warnings_list.append(msg)
    else:
        logger.info("Running velovi.preprocess_data() prior to VELOVI training")
        velovi_preprocess_data(adata)

    VELOVI.setup_anndata(adata, spliced_layer="Ms", unspliced_layer="Mu")
    model = VELOVI(
        adata,
        n_hidden=max(1, int(velovi_n_hidden)),
        n_latent=max(1, int(velovi_n_latent)),
        n_layers=max(1, int(velovi_n_layers)),
        dropout_rate=float(velovi_dropout_rate),
    )
    train_kwargs = {
        "max_epochs": max(1, int(velovi_max_epochs)),
        "lr": float(velovi_lr),
        "weight_decay": float(velovi_weight_decay),
        "batch_size": max(1, int(velovi_batch_size)),
        "early_stopping": bool(velovi_early_stopping),
        "accelerator": "auto",
        "devices": "auto",
    }
    logger.info("Training VELOVI with %s", train_kwargs)
    model.train(**train_kwargs)

    latent_time = _to_numpy(model.get_latent_time(n_samples=max(1, int(velovi_n_samples)))).astype(np.float32, copy=False)
    velocities = _to_numpy(
        model.get_velocity(n_samples=max(1, int(velovi_n_samples)), velo_statistic="mean")
    ).astype(np.float32, copy=False)
    scaling = 20.0 / np.maximum(latent_time.max(axis=0), 1e-6)

    adata.layers["velocity"] = velocities / scaling[np.newaxis, :]
    adata.layers["latent_time_velovi"] = latent_time
    adata.layers["fit_t"] = latent_time * scaling[np.newaxis, :]
    adata.obs["latent_time"] = latent_time.mean(axis=1)
    adata.var["fit_scaling"] = scaling
    adata.var["velocity_genes"] = True

    rates = model.get_rates()
    for source, target in (("alpha", "fit_alpha"), ("beta", "fit_beta"), ("gamma", "fit_gamma")):
        adata.var[target] = _to_numpy(rates[source]).reshape(-1) / scaling

    try:
        switch_time = (
            torch.nn.functional.softplus(model.module.switch_time_unconstr)
            .detach()
            .cpu()
            .numpy()
            .reshape(-1)
        )
        adata.var["fit_t_"] = switch_time * scaling
    except Exception as exc:
        msg = f"VELOVI switch-time export skipped: {exc}"
        logger.warning(msg)
        warnings_list.append(msg)

    graph_kwargs = {"vkey": "velocity", "show_progress_bar": False}
    if velocity_graph_n_neighbors is not None:
        graph_kwargs["n_neighbors"] = max(1, int(velocity_graph_n_neighbors))
    if velocity_graph_sqrt_transform is not None:
        graph_kwargs["sqrt_transform"] = bool(velocity_graph_sqrt_transform)
    if velocity_graph_approx is not None:
        graph_kwargs["approx"] = bool(velocity_graph_approx)

    logger.info("Running velocity_graph on VELOVI output with %s", graph_kwargs)
    scv.tl.velocity_graph(adata, **graph_kwargs)

    try:
        scv.tl.velocity_confidence(adata, vkey="velocity")
    except Exception as exc:
        msg = f"velocity_confidence failed: {exc}"
        logger.warning(msg)
        warnings_list.append(msg)

    try:
        scv.tl.velocity_pseudotime(adata, vkey="velocity")
    except Exception as exc:
        msg = f"velocity_pseudotime failed: {exc}"
        logger.warning(msg)
        warnings_list.append(msg)

    graph_params = {
        "n_neighbors": _coerce_positive_int(velocity_graph_n_neighbors),
        "sqrt_transform": velocity_graph_sqrt_transform,
        "approx": velocity_graph_approx,
    }
    model_params = {
        "n_hidden": max(1, int(velovi_n_hidden)),
        "n_latent": max(1, int(velovi_n_latent)),
        "n_layers": max(1, int(velovi_n_layers)),
        "dropout_rate": float(velovi_dropout_rate),
        "max_epochs": max(1, int(velovi_max_epochs)),
        "lr": float(velovi_lr),
        "weight_decay": float(velovi_weight_decay),
        "batch_size": max(1, int(velovi_batch_size)),
        "n_samples": max(1, int(velovi_n_samples)),
        "early_stopping": bool(velovi_early_stopping),
        "use_highly_variable": bool(velocity_use_highly_variable),
    }

    return _finalize_summary(
        adata,
        method="velovi",
        engine="velovi",
        cluster_key=cluster_key,
        warnings_list=warnings_list,
        preprocess_params=preprocess_params,
        graph_params=graph_params,
        model_params=model_params,
    )


def run_velocity(
    adata,
    *,
    method: str = "stochastic",
    cluster_key: str = "leiden",
    velocity_min_shared_counts: int = COMMON_PREPROCESS_DEFAULTS["velocity_min_shared_counts"],
    velocity_n_top_genes: int = COMMON_PREPROCESS_DEFAULTS["velocity_n_top_genes"],
    velocity_n_pcs: int = COMMON_PREPROCESS_DEFAULTS["velocity_n_pcs"],
    velocity_n_neighbors: int = COMMON_PREPROCESS_DEFAULTS["velocity_n_neighbors"],
    velocity_use_highly_variable: bool = COMMON_PREPROCESS_DEFAULTS["velocity_use_highly_variable"],
    velocity_fit_offset: bool = SCVELO_CORE_DEFAULTS["velocity_fit_offset"],
    velocity_fit_offset2: bool = SCVELO_CORE_DEFAULTS["velocity_fit_offset2"],
    velocity_min_r2: float = SCVELO_CORE_DEFAULTS["velocity_min_r2"],
    velocity_min_likelihood: float = SCVELO_CORE_DEFAULTS["velocity_min_likelihood"],
    velocity_graph_n_neighbors: int | None = COMMON_GRAPH_DEFAULTS["velocity_graph_n_neighbors"],
    velocity_graph_sqrt_transform: bool | None = COMMON_GRAPH_DEFAULTS["velocity_graph_sqrt_transform"],
    velocity_graph_approx: bool | None = COMMON_GRAPH_DEFAULTS["velocity_graph_approx"],
    dynamical_n_top_genes: int | None = DYNAMICAL_DEFAULTS["dynamical_n_top_genes"],
    dynamical_max_iter: int = DYNAMICAL_DEFAULTS["dynamical_max_iter"],
    dynamical_fit_time: bool = DYNAMICAL_DEFAULTS["dynamical_fit_time"],
    dynamical_fit_scaling: bool = DYNAMICAL_DEFAULTS["dynamical_fit_scaling"],
    dynamical_fit_steady_states: bool = DYNAMICAL_DEFAULTS["dynamical_fit_steady_states"],
    dynamical_n_jobs: int | None = DYNAMICAL_DEFAULTS["dynamical_n_jobs"],
    velovi_n_hidden: int = VELOVI_DEFAULTS["velovi_n_hidden"],
    velovi_n_latent: int = VELOVI_DEFAULTS["velovi_n_latent"],
    velovi_n_layers: int = VELOVI_DEFAULTS["velovi_n_layers"],
    velovi_dropout_rate: float = VELOVI_DEFAULTS["velovi_dropout_rate"],
    velovi_max_epochs: int = VELOVI_DEFAULTS["velovi_max_epochs"],
    velovi_lr: float = VELOVI_DEFAULTS["velovi_lr"],
    velovi_weight_decay: float = VELOVI_DEFAULTS["velovi_weight_decay"],
    velovi_batch_size: int = VELOVI_DEFAULTS["velovi_batch_size"],
    velovi_n_samples: int = VELOVI_DEFAULTS["velovi_n_samples"],
    velovi_early_stopping: bool = VELOVI_DEFAULTS["velovi_early_stopping"],
) -> dict:
    """Run the requested RNA velocity method and return a unified summary."""
    if method not in SUPPORTED_METHODS:
        raise ValueError(f"Unknown method '{method}'. Choose from: {SUPPORTED_METHODS}")

    validate_velocity_layers(adata)
    logger.info(
        "Velocity input: %s cells x %s genes, method=%s, cluster_key=%s",
        adata.n_obs,
        adata.n_vars,
        method,
        cluster_key,
    )

    if method == "velovi":
        result = run_velovi(
            adata,
            cluster_key=cluster_key,
            velocity_min_shared_counts=velocity_min_shared_counts,
            velocity_n_top_genes=velocity_n_top_genes,
            velocity_n_pcs=velocity_n_pcs,
            velocity_n_neighbors=velocity_n_neighbors,
            velocity_use_highly_variable=velocity_use_highly_variable,
            velocity_graph_n_neighbors=velocity_graph_n_neighbors,
            velocity_graph_sqrt_transform=velocity_graph_sqrt_transform,
            velocity_graph_approx=velocity_graph_approx,
            velovi_n_hidden=velovi_n_hidden,
            velovi_n_latent=velovi_n_latent,
            velovi_n_layers=velovi_n_layers,
            velovi_dropout_rate=velovi_dropout_rate,
            velovi_max_epochs=velovi_max_epochs,
            velovi_lr=velovi_lr,
            velovi_weight_decay=velovi_weight_decay,
            velovi_batch_size=velovi_batch_size,
            velovi_n_samples=velovi_n_samples,
            velovi_early_stopping=velovi_early_stopping,
        )
    else:
        result = run_scvelo(
            adata,
            mode=method,
            cluster_key=cluster_key,
            velocity_min_shared_counts=velocity_min_shared_counts,
            velocity_n_top_genes=velocity_n_top_genes,
            velocity_n_pcs=velocity_n_pcs,
            velocity_n_neighbors=velocity_n_neighbors,
            velocity_use_highly_variable=velocity_use_highly_variable,
            velocity_fit_offset=velocity_fit_offset,
            velocity_fit_offset2=velocity_fit_offset2,
            velocity_min_r2=velocity_min_r2,
            velocity_min_likelihood=velocity_min_likelihood,
            velocity_graph_n_neighbors=velocity_graph_n_neighbors,
            velocity_graph_sqrt_transform=velocity_graph_sqrt_transform,
            velocity_graph_approx=velocity_graph_approx,
            dynamical_n_top_genes=dynamical_n_top_genes,
            dynamical_max_iter=dynamical_max_iter,
            dynamical_fit_time=dynamical_fit_time,
            dynamical_fit_scaling=dynamical_fit_scaling,
            dynamical_fit_steady_states=dynamical_fit_steady_states,
            dynamical_n_jobs=dynamical_n_jobs,
        )

    return {"n_cells": int(adata.n_obs), "n_genes": int(adata.n_vars), **result}
